sudo: required
language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
services:
  - docker
before_script:
  - ./bin/server -d
  - |
    until nc -z -v -w30 127.0.0.1 7419
    do
      sleep 1
    done
script:
  - npm run lint
  - npm run build
  - npm test
after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
